### PR TITLE
Max 10 Vaults 

### PR DESCRIPTION
**Pull request by wjdavis5**
*Issue #, if available:*
https://github.com/aws/aws-sdk-net/issues/895#issuecomment-372345218

*Description of changes:*
Changed to return max 10 vaults.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by wjdavis5** [comment]
Hello, any updates on this?

**Comment by RandyOcheltree** [comment]
Thanks for your feedback. I need to confirm this change and then I'll make the update.

**Comment by wjdavis5** [comment]
Hello, any updates on this?

**Comment by RandyOcheltree** [comment]
Thanks again for your feedback!

**Pull request merged**
